package lk.ijse.plantLife.utill;

public enum TextFields {
    ID,LANKAN_ID,NAME,EMAIL,PHONE,INTEGER,DOUBLE,ADDRESS,NONE_CHARACTER,INVOICE,TEXT_SPACE_NUMBER,
    MEMBER_ID,DIET_PLAN_ID,INV_ID,SCH_ID
}
